###
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jk",
    "password": "sala"
}

###
GET http://localhost:3000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzY5NzA1MTM5LCJleHAiOjE3Njk3MDg3Mzl9.XQY2z7c3VDLiH5XAQHcbACkoxkT7rjcuk-pbLgni84E

###
GET http://localhost:3000/data/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzY5NzA1MTM5LCJleHAiOjE3Njk3MDg3Mzl9.XQY2z7c3VDLiH5XAQHcbACkoxkT7rjcuk-pbLgni84E

###
POST http://localhost:3000/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzY5NzA1MTM5LCJleHAiOjE3Njk3MDg3Mzl9.XQY2z7c3VDLiH5XAQHcbACkoxkT7rjcuk-pbLgni84E

{
    "id": "5",
    "Firstname": "Donald",
    "Surname": "Duck",
    "userid": "jk"
}

###
GET http://localhost:3000/doc

###
DELETE http://localhost:3000/data/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzY5NzA1MTM5LCJleHAiOjE3Njk3MDg3Mzl9.XQY2z7c3VDLiH5XAQHcbACkoxkT7rjcuk-pbLgni84E

###
PUT http://localhost:3000/data/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzY5NzA1MTM5LCJleHAiOjE3Njk3MDg3Mzl9.XQY2z7c3VDLiH5XAQHcbACkoxkT7rjcuk-pbLgni84E

{
    "Firstname": "Mickey",
    "Surname": "Mouse"
}